package ServerModule;

/**
* ServerModule/ServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterface.idl
* Wednesday, February 26, 2020 2:36:41 o'clock PM EST
*/

public final class ServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerModule.ServerInterface value = null;

  public ServerInterfaceHolder ()
  {
  }

  public ServerInterfaceHolder (ServerModule.ServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerModule.ServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerModule.ServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerModule.ServerInterfaceHelper.type ();
  }

}
