package ServerModule;


/**
* ServerModule/ServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterface.idl
* Wednesday, February 26, 2020 2:36:41 o'clock PM EST
*/

public interface ServerInterface extends ServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInterface
